export const copy = {
  en: {
    nav: ['The experience', 'Made for you', 'Open source'], get: 'Get Nova', skip: 'Skip to content',
    hero: ['A little more space.', 'A lot more possibility.'],
    intro: 'Meet Nova. A calmer, more personal browser with local AI, thoughtful workspaces, and privacy built in.',
    download: 'Download Nova', watch: 'Take a closer look', available: 'Free for macOS, Windows & Linux',
    screenshot: 'Nova’s new tab page with a blue landscape, clock, and search field',
    note: 'Room to think. Space to explore.',
    principles: ['Your AI, on your device', 'Your tabs, beautifully organized', 'Your browser, open source'],
    experienceTitle: ['Less in your way.', 'More in your flow.'],
    experienceText: 'A fresh start for everything you do online. Make room for the things that matter, and make yourself at home.',
    tabs: ['Your space', 'Your assistant', 'Your devices'],
    tabTitles: ['A home for your curiosity.', 'A little help, right where you are.', 'Pick up where you left off.'],
    tabText: ['Separate work from everything else. Choose vertical or horizontal tabs, create workspaces, and give every idea a place to land.', 'Ask questions and explore ideas with local AI in your sidebar. Supported models run on your device with WebGPU after the initial download.', 'Keep bookmarks and passwords in reach across your computers with encrypted Nova Sync. Pair devices with a code, without an email or password.'],
    tabDetails: ['Workspaces · Flexible tabs · Split view', 'Local inference · WebGPU · Sidebar assistant', 'Encrypted sync · Device pairing · AES-256-GCM'],
    tabAlt: ['Nova browser new tab page', 'Nova AI sidebar answering a request to list open tabs', 'Nova Sync device pairing dialog'],
    previewCaption: 'Actual Nova interface. Appearance may vary by platform.',
    personalTitle: ['A browser that’s', 'on your side.'],
    personalText: 'Useful by design. Personal by default. The details make all the difference.',
    privacyTitle: 'A quieter corner of the internet.',
    privacyText: 'Built-in network filtering blocks ads and known trackers, so there’s less between you and what you came for.',
    privacyLink: 'Explore the privacy features',
    aiTitle: 'Big ideas. Local intelligence.',
    aiText: 'Give your curiosity a capable companion. Nova’s local AI brings answers into your browsing flow, with inference on your own hardware.',
    aiNote: 'Model download and compatible hardware required.',
    detailTitles: ['Keep your favorites.', 'Give every project its place.', 'Bring your agents along.'],
    detailTexts: ['Use Chrome Web Store extensions and bring familiar tools into your new space.', 'Workspaces, split view, and sleeping tabs help you keep a busy day organized.', 'Connect compatible coding agents through Nova’s built-in local MCP server.'],
    sourceTitle: ['An open browser.', 'A shared possibility.'],
    sourceText: 'Nova is open source, from the first tab to the last line of code. Explore how it works, report an idea, or help shape what comes next.',
    sourceLink: 'Explore on GitHub', sourceNote: 'Built in the open. Licensed under MIT.',
    faqTitle: 'A few things to know.',
    faq: [
      ['Is Nova free?', 'Yes. Nova is free and open source under the MIT license. You can download the browser, inspect the code, and contribute on GitHub.'],
      ['Which computers can run Nova?', 'Nova has releases for macOS on Apple Silicon and Intel, Windows x64, and Linux x64. Choose the installer for your operating system below.'],
      ['How does local AI work?', 'Nova uses WebGPU to run supported AI models on your device. You need to download a model first, and availability and speed depend on your graphics hardware and memory. External agents and providers have their own data handling.'],
      ['Can I use my existing extensions?', 'Nova supports Chrome Web Store extensions. Compatibility can vary by extension; visit the project on GitHub if you run into a problem.'],
      ['How does Nova Sync protect my data?', 'Nova Sync encrypts your bookmarks and passwords on your device with AES-256-GCM. Pair your computers using a sync code; keep that code private because it gives access to the encrypted data.'],
    ],
    downloadTitle: ['Make a little', 'room for Nova.'],
    downloadText: 'Your next favorite place on the internet starts here.',
    release: 'Release', installer: 'Choose your installer', allReleases: 'All releases & checksums',
    desktopNote: 'Nova is a desktop browser. Download it on your computer.',
    footerLine: 'A more personal internet.', footerLinks: ['Source code', 'Release notes', 'Report an issue'],
    footerBottom: 'Made for the way you explore.', language: 'Switch to Turkish', menu: 'Open navigation', close: 'Close',
    videoTitle: 'A closer look at Nova', videoDescription: 'A silent product walkthrough of Nova’s browsing interface.',
  },
  tr: {
    nav: ['Deneyim', 'Senin için', 'Açık kaynak'], get: 'Nova’yı edin', skip: 'İçeriğe geç',
    hero: ['Biraz daha alan.', 'Çok daha fazla olasılık.'],
    intro: 'Nova ile tanış. Yerel yapay zekâ, düzenli çalışma alanları ve yerleşik gizlilikle daha sakin, daha kişisel bir tarayıcı.',
    download: 'Nova’yı indir', watch: 'Yakından keşfet', available: 'macOS, Windows ve Linux için ücretsiz',
    screenshot: 'Nova’nın mavi manzaralı, saat ve arama alanı içeren yeni sekme sayfası',
    note: 'Düşünmek için alan. Keşfetmek için özgürlük.',
    principles: ['Yapay zekân, kendi cihazında', 'Sekmelerin, tam istediğin düzende', 'Tarayıcın, açık kaynak'],
    experienceTitle: ['Daha az karmaşa.', 'Daha çok odak.'],
    experienceText: 'İnternette yaptığın her şey için yeni bir başlangıç. Önem verdiğin şeylere yer aç, kendini evinde hisset.',
    tabs: ['Senin alanın', 'Senin asistanın', 'Senin cihazların'],
    tabTitles: ['Merakına yer aç.', 'İhtiyacın olan yerde, küçük bir yardım.', 'Kaldığın yerden devam et.'],
    tabText: ['İşini ve kişisel dünyanı ayır. Dikey ya da yatay sekmeleri seç, çalışma alanları oluştur ve her fikrine bir yer aç.', 'Kenar çubuğundaki yerel yapay zekâ ile sorular sor, fikirlerini geliştir. Desteklenen modeller ilk indirmeden sonra WebGPU ile cihazında çalışır.', 'Şifreli Nova Sync ile yer imlerin ve parolaların bilgisayarların arasında seninle gelsin. E-posta veya parola olmadan, bir kodla eşleştir.'],
    tabDetails: ['Çalışma alanları · Esnek sekmeler · Bölünmüş görünüm', 'Yerel işlem · WebGPU · Kenar çubuğu asistanı', 'Şifreli senkronizasyon · Cihaz eşleştirme · AES-256-GCM'],
    tabAlt: ['Nova tarayıcı yeni sekme sayfası', 'Açık sekmeleri listeleyen Nova AI kenar çubuğu', 'Nova Sync cihaz eşleştirme penceresi'],
    previewCaption: 'Gerçek Nova arayüzü. Görünüm platforma göre değişebilir.',
    personalTitle: ['Senin tarafında', 'bir tarayıcı.'],
    personalText: 'Kullanışlı tasarım. Kişisel bir deneyim. Farkı yaratan, küçük ayrıntılar.',
    privacyTitle: 'İnternetin daha sakin bir köşesi.',
    privacyText: 'Yerleşik ağ filtreleme, reklamları ve bilinen izleyicileri engeller. Seninle aradığın şeyin arasındaki kalabalık azalır.',
    privacyLink: 'Gizlilik özelliklerini keşfet',
    aiTitle: 'Büyük fikirler. Yerel zekâ.',
    aiText: 'Merakına yetenekli bir yol arkadaşı bul. Nova’nın yerel yapay zekâsı, işlemleri kendi donanımında yaparak yanıtları tarayıcına getirir.',
    aiNote: 'Model indirmesi ve uyumlu donanım gerekir.',
    detailTitles: ['Favorilerinden vazgeçme.', 'Her projeye kendi alanı.', 'Ajanlarını da yanında getir.'],
    detailTexts: ['Chrome Web Store uzantılarını kullan, alıştığın araçları yeni alanına taşı.', 'Çalışma alanları, bölünmüş görünüm ve uyuyan sekmelerle yoğun gününü düzenle.', 'Nova’nın yerleşik yerel MCP sunucusu üzerinden uyumlu kodlama ajanlarını bağla.'],
    sourceTitle: ['Açık bir tarayıcı.', 'Ortak bir gelecek.'],
    sourceText: 'Nova, ilk sekmeden son kod satırına kadar açık kaynak. Nasıl çalıştığını keşfet, fikrini paylaş veya geleceğini birlikte şekillendirelim.',
    sourceLink: 'GitHub’da keşfet', sourceNote: 'Açık geliştiriliyor. MIT lisansıyla sunuluyor.',
    faqTitle: 'Merak ettiklerin.',
    faq: [
      ['Nova ücretsiz mi?', 'Evet. Nova, MIT lisansıyla sunulan ücretsiz ve açık kaynak bir tarayıcı. İndirebilir, kodunu inceleyebilir ve GitHub üzerinden katkıda bulunabilirsin.'],
      ['Hangi bilgisayarlarda çalışır?', 'Nova; Apple Silicon ve Intel işlemcili macOS, Windows x64 ve Linux x64 için sürümler sunar. Aşağıdan işletim sistemine uygun kurulum dosyasını seçebilirsin.'],
      ['Yerel yapay zekâ nasıl çalışır?', 'Nova, desteklenen modelleri cihazında çalıştırmak için WebGPU kullanır. Önce bir model indirmen gerekir; kullanılabilirlik ve hız, grafik donanımına ve belleğine bağlıdır. Harici ajan ve sağlayıcıların kendi veri işleme koşulları vardır.'],
      ['Mevcut uzantılarımı kullanabilir miyim?', 'Nova, Chrome Web Store uzantılarını destekler. Uyumluluk uzantıya göre değişebilir; bir sorunla karşılaşırsan GitHub üzerinden bildirebilirsin.'],
      ['Nova Sync verilerimi nasıl korur?', 'Nova Sync, yer imlerini ve parolalarını cihazında AES-256-GCM ile şifreler. Bilgisayarlarını senkronizasyon koduyla eşleştirirsin. Şifreli verilere erişim sağladığı için bu kodu gizli tutmalısın.'],
    ],
    downloadTitle: ['Nova’ya', 'biraz yer aç.'],
    downloadText: 'İnternetteki yeni favori yerin burada başlıyor.',
    release: 'Sürüm', installer: 'Kurulum dosyanı seç', allReleases: 'Tüm sürümler ve sağlama toplamları',
    desktopNote: 'Nova bir masaüstü tarayıcısı. Bilgisayarından indirebilirsin.',
    footerLine: 'Daha kişisel bir internet.', footerLinks: ['Kaynak kodu', 'Sürüm notları', 'Sorun bildir'],
    footerBottom: 'Senin keşif biçimin için.', language: 'Switch to English', menu: 'Menüyü aç', close: 'Kapat',
    videoTitle: 'Nova’ya yakından bak', videoDescription: 'Nova’nın tarayıcı arayüzünü gösteren sessiz ürün turu.',
  },
}
