process.on('unhandledRejection', (reason) => {
  console.error('Unhandled Rejection in test suite:', reason);
  process.exit(1);
});
process.on('uncaughtException', (err) => {
  console.error('Uncaught Exception in test suite:', err);
  process.exit(1);
});

console.log('Executing all test suites...');
import './e2e/tier1_feature_coverage.test';
import './e2e/tier2_boundary_corner.test';
import './e2e/tier3_cross_feature.test';
import './e2e/tier4_real_world.test';
import './e2e/tier5_adversarial_stress.test';
import './challenger2_empirical_verification';
import './challenger_iter2_stress';
import './challenger_m1_security_empirical';
import './m1_adversarial_security.test';
import './m2_adversarial_empirical.test';
import './m3_performance_memoization.test';
import './challenger_m3_performance_empirical';
import './main_process_runtime_verification';
import './challenger_m4_bundle_empirical';
import './securityHardening.test';
import './page_translation.test';
import './security_regression_audit.test';
import './ssrf_ip_policy.test';
import './vertical_tabs.test';
import './safe_navigation_comprehensive.test';
import './search_engine_formatting.test';
import './security_utils_classification.test';
import './ai_memory_security.test';
import './link_preview_lru.test';
import './workspace_state_management.test';
import './adblock_filter_engine.test';
import './keyboard_shortcuts.test';
import './reader_mode_sanitization.test';
import './session_isolation.test';
import './history_bookmarks_search.test';
import './ai_agent_tools.test';
import './webllm_config.test';
import './adversarial_hacker_security.test';
