// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/flagship-reveal.scene.json";
export const sceneModules = {
  "src/flute/scenes/flagship-reveal.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/flagship-reveal.tsx": () => import("./scenes/flagship-reveal"),
};
